django_recipe/mysite/main/urls.py
from django.urls import path

from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('adddata/', views.addData, name="addData"),
    path('allrecipes/', views.allRecipes, name="allRecipes"),
    path('myrecipes/', views.myrecipes, name='myrecipes'),
    path('ingredients/', views.ingredientPicker, name='ingredientPicker'),
    path('home/',views.index, name='index'),
    path('grocerylist/', views.groceryList, name='groceryList'),
    path('like/', views.like, name='like'),
    path('add_recipe/', views.add_recipe, name='add_recipe'),
    path('liked_recipes/',views.liked_recipes, name='liked_recipes'),
    path('showmore/',views.showmore, name='showmore'),
    path('dislike/', views.dislike, name='dislike'),
    path('add_ingredient/', views.add_ingredient, name="add_ingredient"),
    path('checky/', views.checky, name="checky"),
]

django_recipe/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from register import views as v
import debug_toolbar
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path("register/", v.register, name="register"),
    path('', include("django.contrib.auth.urls")),
    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += staticfiles_urlpatterns()

django_recipe/mysite/main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class recipes3(models.Model):
    name = models.CharField(max_length=200)
    time = models.PositiveIntegerField(null=True, blank=True)
    url = models.URLField(max_length=200)
    image = models.CharField(max_length=200)
    calories = models.FloatField(null=True, blank=True)
    ingredients = models.ManyToManyField('ingredients3', related_name='recipes')
    genre = models.ManyToManyField('genres3', related_name='recipes')
    liked =models.ManyToManyField(User, related_name='liked')
    disliked =models.ManyToManyField(User, related_name='disliked')
    checked =models.ManyToManyField(User, related_name='checked')

    def __str__(self):
        return self.name

class ingredients3(models.Model):
    name = models.CharField(max_length=200)
    checked =models.ManyToManyField(User, related_name='ing_checked')
    or_ing = models.BooleanField(default=False)
    def __str__(self):
        return self.name
        
class genres3(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name
        
class recipe_ingredients3(models.Model):
    recipe = models.ForeignKey('recipes3', related_name='ingredient_amounts', on_delete=models.SET_NULL, null=True)
    ingredient = models.ForeignKey('ingredients3', related_name='ingredient_amounts', on_delete=models.SET_NULL, null=True, blank=True)
    amount = models.FloatField(blank=True, null=True)
    unit = models.CharField(max_length=50, blank=True, null=True)
    def __str__(self):
        return f'RECIPE: {self.recipe.name} INGREDIENT: {self.ingredient.name}'

class or_ingredients(models.Model):
    or_name = models.ForeignKey('ingredients3', related_name='or_ingredient', on_delete=models.SET_NULL, null=True)
    in_name = models.ForeignKey('ingredients3', related_name='in_ingredient', on_delete=models.SET_NULL, null=True)

class user_recipes(models.Model):
    recipe = models.ForeignKey('recipes3', related_name='user_recipe', on_delete=models.SET_NULL, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="recipes", null=True)
    percent = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return str(self.id)

class grocery_list(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="recipe_list", null=True)
    name = models.ForeignKey('ingredients3', related_name='recipe_list', on_delete=models.SET_NULL, null=True, blank=True)
    amount = models.FloatField(blank=True, null=True)
    unit = models.CharField(max_length=50, blank=True, null=True)
    checked = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)

django_recipe/mysite/main/views.py
from os import name
from django.db.models.query import QuerySet, Prefetch
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from .models import or_ingredients, recipe_ingredients3, recipes3, ingredients3, genres3, user_recipes, grocery_list
import csv
from django import template
import inflect
from .funky import add_up, sub_out
from django.core.paginator import Paginator
import json

def checky(request):
    if request.POST.get('action') == 'post':
        id = request.POST.get('postid')
        grocery = grocery_list.objects.get(pk=id)
        if grocery.checked == True:
            grocery.checked = False
            grocery.save()
            checked = 'no'
        else:
            grocery.checked = True
            grocery.save()
            checked = 'yes'

        return JsonResponse({'id': id, 'checked': checked})

def add_ingredient(request):
    print("yes")
    if request.POST.get('action') == 'post':
        id = request.POST.get('postid')
        ingredient_list = []
        ingredient = ingredients3.objects.get(pk=id)
        if request.user not in ingredient.checked.all():
            print("action to check")
            ingredient.checked.add(request.user)
            ingredient_list.append(ingredient)
            if or_ingredients.objects.filter(in_name=ingredient).exists():
                print('exists')
                for or_name in or_ingredients.objects.filter(in_name=ingredient):  
                    thing = ingredients3.objects.get(name=or_name.or_name)
                    thing.checked.add(request.user)
                    ingredient_list.append(thing)

            for sel_ing in ingredient_list:
                recipes = recipe_ingredients3.objects.select_related('recipe').filter(ingredient = sel_ing)
                for recipe in recipes:
                    total = recipe.recipe.ingredients.all().count()
                    print(recipe.recipe.name)
                    print(total)
                    percent = (1 / total) * 100
                    percent = round(percent, 0)
                    entry, created = user_recipes.objects.get_or_create(recipe = recipe.recipe, user = request.user)
                    if created:
                        entry.percent = 0
                    print(f'before percent:', entry.percent)
                    entry.percent = entry.percent + percent
                    entry.save()
                    print(f'after percent:', entry.percent)
        else:
            print('action to not check')
            ingredient.checked.remove(request.user)
            ingredient_list.append(ingredient)
            if or_ingredients.objects.filter(in_name=ingredient).exists():
                print('exists')
                for or_name in or_ingredients.objects.filter(in_name=ingredient):  
                    thing = ingredients3.objects.get(name=or_name.or_name)
                    thing.checked.remove(request.user)
                    ingredient_list.append(thing)

            for sel_ing in ingredient_list:
                recipes = recipe_ingredients3.objects.select_related('recipe').filter(ingredient = sel_ing)
                for recipe in recipes:
                    total = recipe.recipe.ingredients.all().count()
                    print(f'NEW RECIPE:', recipe.recipe.name)
                    print(f'Total ingredients:', total)
                    percent = (1 / total) * 100
                    percent = round(percent, 0)
                    entry, created = user_recipes.objects.get_or_create(recipe = recipe.recipe, user = request.user)
                    if created:
                        entry.percent = 0
                    print(f'before percent:', entry.percent)
                    entry.percent = entry.percent - percent
                    entry.save()
                    print(f'after percent:', entry.percent)

        return JsonResponse({'id': id})

def index(response):
    return render(response, "main/home.html")

def showmore(request):
    if request.POST.get('action') == 'post':
        id = int(request.POST.get('postid'))
        recipe = recipes3.objects.get(id=id)

        calories = str(recipe.calories) + ' Calories'
        time = str(recipe.time) + ' Minutes'

        genres = ''
        for genre in recipe.genre.all():
            if genres == '':
                genres = str(genre)
            else:
                genres = genres + ' ,' + str(genre)

        print(recipe.name)
        print(calories)
        print(genres)
        return JsonResponse({'id': recipe.id, 'calories': calories, 'time': time, 'genres': genres })

def like(request):
    if request.POST.get('action') == 'post':
        id = int(request.POST.get('postid'))
        recipe = recipes3.objects.get(id=id)
        if request.user in recipe.liked.all():
            print('unliked')
            result = 'unliked'
            recipe.liked.remove(request.user)
        else:
            if request.user in recipe.disliked.all():
                recipe.disliked.remove(request.user)
            result = 'liked'
            print('liked')
            recipe.liked.add(request.user)
        return JsonResponse({'id': recipe.id, 'result': result})

def dislike(request):
    if request.POST.get('action') == 'post':
        id = int(request.POST.get('postid'))
        recipe = recipes3.objects.get(id=id)
        if request.user in recipe.disliked.all():
            print('undisliked')
            result = 'undisliked'
            recipe.disliked.remove(request.user)
        else:
            if request.user in recipe.liked.all():
                recipe.liked.remove(request.user)
            recipe.disliked.add(request.user)
            result = 'disliked'
            print('disliked')

        return JsonResponse({'result': result, 'id': id})


def add_recipe(request):
    if request.POST.get('action') == 'post':
        id = request.POST.get('postid')
        recipe = recipes3.objects.get(id=id)

        if request.user in recipe.checked.all():
            result = 'unchecked'
            sub_out(recipe, request.user)
            print(result)
        else:
            result = 'checked'
            add_up(recipe, request.user)
            print(result)

        return JsonResponse({'result': result, 'id':id})

def allRecipes(response):
    if response.user.is_authenticated:
        orderby = meal_type = veggie = vegan = gluten_free = 'none'
        if response.method == 'POST':
            print(response.POST)
            posts = recipes3.objects.prefetch_related('checked', 'liked', 'disliked').order_by('name')
            if response.POST.get('save'):
                genres = genres3.objects.all()
                if response.POST.__contains__('meal_type'):
                    meal0 = response.POST.get('meal_type')
                    if meal0 =='lunch':
                        breakfast = genres.get(name='breakfast')
                        dessert = genres.get(name='dessert')
                        posts = posts.exclude(genre=breakfast).exclude(genre=dessert)
                        meal_type = 'lunch'
                    else:
                        # meal = genres3.objects.get(name=meal0)
                        meal = genres.get(name=meal0)
                        posts = posts.filter(genre=meal.id)
                        meal_type = meal0

                if response.POST.__contains__('restrict'):
                    restricts = response.POST.getlist('restrict')
                    for restrict in restricts:
                        if restrict == 'gluten':
                            restrict = 'gluten free'
                            gluten_free = restrict
                            print('GLUTEN')
                        if restrict == 'vegeterian':
                            veggie = restrict
                            print('VEGGIE')
                            print(veggie)
                        if restrict == 'vegan':
                            vegan = restrict
                            print(vegan)
                        restricter = genres.get(name=restrict)
                        posts = posts.filter(genre=restricter)

                if response.POST.__contains__('orderby'):
                    order = response.POST.get('orderby')
                    orderby = order
                    if order == 'calories':
                        posts = posts.exclude(calories=0).order_by('calories')
                    else:
                        posts = posts.exclude(time=0).order_by('time')
                else:
                    posts = posts.order_by('name')

            paginator = Paginator(posts, 25)
            page = response.GET.get('page')
            posts = paginator.get_page(page)

            return render(response, "main/allrecipes.html", {'posts':posts, 'orderby': orderby, 'meal_type': meal_type, 'veggie':veggie, 'vegan':vegan, 'gluten_free': gluten_free})
        
        else:
            posts = recipes3.objects.prefetch_related('checked', 'liked', 'disliked').order_by('name')
            paginator = Paginator(posts, 25)
            page = response.GET.get('page')
            posts = paginator.get_page(page)
            
            return render(response, "main/allrecipes.html", {'posts':posts, 'user': response.user, 'orderby': orderby, 'meal_type': meal_type, 'veggie':veggie, 'vegan':vegan, 'gluten_free': gluten_free})
    else:
        return render(response, "main/allrecipes.html")


def ingredientPicker(response):
    if response.user.is_authenticated:
        if response.method == 'POST':
            print(response.POST)
            if response.POST.get('save') == 'select':
                non_ors = response.user.ing_checked.exclude(or_ing=True)
                return render(response, "main/ingredient.html", {'non_ors': non_ors, 'selected': 'no selected', 'user': response.user})
            elif response.POST.get('save') == 'no select':

django_recipe/mysite/main/templates/main/allrecipes.html
{% extends "main/base.html" %}
{% block title %}All Recipes {% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'main/css/allrecipes.css' %}">
<link rel="stylesheet" href="{% static 'main/css/pagination_blue.css' %}">

  {% if user.is_authenticated%}
    <div id= "title" class="row topper" style="justify-content: space-around;">
      <h1>Explore All Recipes</h1>
    </div>
    <div class="row topper" style="justify-content: space-around;">
      <h3>Filters:</h3>
    </div>
    <form method="post" action="#">
      {% csrf_token %}
    <div class="row">
        <div class="col-12 col-md-4 text-center">
          <h4 class=text-center>Sort by</h4>
          {% if orderby == 'none' %}
            <input type='radio' id='calories' name='orderby' value='calories'>
            <label for='calories'>Calories</label><br>
            <input type='radio' id='time' name='orderby' value='time'>
            <label for='time'>Time</label><br>
          {% elif orderby == 'calories' %}
            <input type='radio' id='calories' name='orderby' value='calories' checked>
            <label for='calories'>Calories</label><br>
            <input type='radio' id='time' name='orderby' value='time'>
            <label for='time'>Time</label><br>
          {% else %}
            <input type='radio' id='calories' name='orderby' value='calories' checked>
            <label for='calories'>Calories</label><br>
            <input type='radio' id='time' name='orderby' value='time' checked>
            <label for='time'>Time</label><br>
          {% endif %}
        
        </div>
        <div class="col-12 col-md-4 text-center">
          <h4 class=text-center>Special Diet</h4>
            {% if veggie == 'none' %}
            <input type='checkbox' id='vegeterian' name='restrict' value='vegeterian'>
            {% else %}
            <input type='checkbox' id='vegeterian' name='restrict' value='vegeterian' checked>
            {% endif %}
            <label for='vegeterian'>Vegeterian</label><br>
            {% if vegan == 'none' %}
            <input type='checkbox' id='vegan' name='restrict' value='vegan'>
            {% else %}
            <input type='checkbox' id='vegan' name='restrict' value='vegan' checked>
            {% endif %}
            <label for='vegan'>Vegan</label><br>
            {% if gluten_free == 'none' %}
            <input type='checkbox' id='gluten' name='restrict' value='gluten'>
            {% else %}
            <input type='checkbox' id='gluten' name='restrict' value='gluten' checked>
            {% endif %}
            <label for='gluten'>Gluten Free</label><br>
        </div>
        <div class="col-12 col-md-4 text-center">
          <h4 class=text-center>Meal Type</h4>
            {% if meal_type == 'none' %}
            <input type='radio' id='breakfast' name='meal_type' value='breakfast'>
            <label for='breakfast'>Breakfast</label><br>
            <input type='radio' id='lunch' name='meal_type' value='lunch'>
            <label for='lunch'>Lunch/Dinner</label><br>
            <input type='radio' id='dessert' name='meal_type' value='dessert'>
            <label for='dessert'>Dessert</label><br>
            {% elif meal_type == 'lunch' %}
            <input type='radio' id='breakfast' name='meal_type' value='breakfast'>
            <label for='breakfast'>Breakfast</label><br>
            <input type='radio' id='lunch' name='meal_type' value='lunch' checked>
            <label for='lunch'>Lunch/Dinner</label><br>
            <input type='radio' id='dessert' name='meal_type' value='dessert'>
            <label for='dessert'>Dessert</label><br>
            {% elif meal_type == 'breakfast' %}
            <input type='radio' id='breakfast' name='meal_type' value='breakfast' checked>
            <label for='breakfast'>Breakfast</label><br>
            <input type='radio' id='lunch' name='meal_type' value='lunch'>
            <label for='lunch'>Lunch/Dinner</label><br>
            <input type='radio' id='dessert' name='meal_type' value='dessert'>
            <label for='dessert'>Dessert</label><br>
            {% else %}
            <input type='radio' id='breakfast' name='meal_type' value='breakfast'>
            <label for='breakfast'>Breakfast</label><br>
            <input type='radio' id='lunch' name='meal_type' value='lunch'>
            <label for='lunch'>Lunch/Dinner</label><br>
            <input type='radio' id='dessert' name='meal_type' value='dessert' checked>
            <label for='dessert'>Dessert</label><br>
            {% endif %}
        </div>
    </div>
    <div class="row" style="justify-content: space-around;">
      <button type="submit" id='save' name='save' value='save'>Show Preferences</button>
    </div>
  </form>
  
      <form method="POST" action="#">
        {% csrf_token %}
        <div class="row topper">
          {% for recipe in posts%}
          <div class="col-lg-6 col-md-12 col-sm-12 text-center">
            <div class="recipe-container text-center">
              <a href= {{recipe.url}} target="_blank"><h4 class="recipe-title">{{recipe.name}}</h4></a>
              <div class="img-container position-relative start-50 bottom-50">
                <img src={{recipe.image}} alt='photo of {{recipe.name}}'> 
                {% if user in recipe.checked.all%}
                  <button type="submit", class = 'add-position-fixed', id = 'c{{recipe.id}}' value='{{recipe.id}}'><i class="bi bi-check-lg"></i></button>
                {% else %}
                  <button type="submit", class = 'add-position-fixed', id = 'c{{recipe.id}}' value='{{recipe.id}}'><i class="bi bi-plus-lg"></i></button>
                {% endif %}
                <button type="submit", class = 'showmore-position-fixed', id = 's{{recipe.id}}' value='{{recipe.id}}'><i class="bi bi-three-dots"></i></button>
                <div class='info' id="showmore{{recipe.id}}">
                  <p id="time{{recipe.id}}"></p>
                  <p id="cal{{recipe.id}}"></p>
                  <p id="genres{{recipe.id}}"></p>
                </div>
              </div>
              {% if user in recipe.liked.all %}
                <button type='submit', class = 'like', id = 'l{{recipe.id}}' value='{{recipe.id}}'><i class="bi bi-hand-thumbs-up-fill"></i></button>
              {% else %}
                <button type='submit', class = 'like', id = 'l{{recipe.id}}' value='{{recipe.id}}'><i class="bi bi-hand-thumbs-up"></i></button>
              {% endif %}
              {% if user in recipe.disliked.all%}
                <button type="submit", class = 'dislike', id = 'd{{recipe.id}}' value='{{recipe.id}}'><i class="bi bi-hand-thumbs-down-fill"></i></button>
              {% else %}
                <button type="submit", class = 'dislike', id = 'd{{recipe.id}}' value='{{recipe.id}}'><i class="bi bi-hand-thumbs-down"></i></button>
              {% endif %}
            </div>
          </div>
            {% if forloop.counter|divisibleby:4 %}</div><div class="row">{% endif %}
              {% if forloop.last %}</div>{% endif %}
          {% endfor %}
  
        </form>
        {% if posts.paginator.num_pages > 1 %}
          <div class="pagination">
            {% if posts.has_previous %}
            <a class="pagination-action" href="?page=1">
                <i class="fa fa-angle-double-left" aria-hidden="true"></i> </a>
            <a class="pagination-action" href="?page={{ posts.previous_page_number }}">
                <i class="fa fa-angle-left" aria-hidden="true"></i>
            </a>
            {% endif %}
            {% for num in posts.paginator.page_range %}
                {% if posts.number == num %}
                    <span class="pagination-number pagination-current">{{ num }}</span>
                {% elif num > posts.number|add:'-3' and num < posts.number|add:'3' %}
                    <a class="pagination-number" href="?page={{ num }}">{{ num }}</a>
                {% endif %}
            {% endfor %}
            {% if posts.has_next %}
                <a class="pagination-action" href="?page={{ posts.next_page_number }}">
                    <i class="fa fa-angle-right" aria-hidden="true"></i>
                </a>
                <a class="pagination-action" href="?page={{ posts.paginator.num_pages }}">
                    <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                </a>
            {% endif %}
          </div>
        {% endif %}
    {% else %}
    <a href="/login">Login Here to Access Content</a>
    {% endif%}
    </div>
{% endblock %}

{% block javascript %}
<script>
  $(document).on('click', '.add-position-fixed', function (h) {
    h.preventDefault();
    $(this).attr('disabled', true);
    $.ajax({
    type: 'POST',
    url: '{% url "main:add_recipe" %}',
    data: {
    postid: $(this).val(),
    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
    action: 'post',
    },
    success: function (json) {
        var recipechecked = document.getElementById('c' + json['id']);
        $(recipechecked).attr('disabled', false);
        if (json['result'] == 'checked') {
        recipechecked.innerHTML = '<i class="bi bi-check-lg"></i>'
        }
        else {
        recipechecked.innerHTML = '<i class="bi bi-plus-lg"></i>'
        }
    },
    error: function (xhr, errmsg, err) {

    }
    });
})

$(document).on('click', '.like', function (t) {
    t.preventDefault();
    $.ajax({
    type: 'POST',
    url: '{% url "main:like" %}',
    data: {
        postid: $(this).val(),
        csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
        action: 'post',
    },
    success: function (json) {
        var recipeliked = document.getElementById('l' + json['id']);
        if (json['result'] == 'liked') {
        recipeliked.innerHTML = '<i class="bi bi-hand-thumbs-up-fill"></i>'
        var recipedis = document.getElementById('d' + json['id']);
        recipedis.innerHTML = '<i class="bi bi-hand-thumbs-down"></i>'
        }
        else {
        recipeliked.innerHTML = '<i class="bi bi-hand-thumbs-up"></i>'
        }
    },
    error: function (xhr, errmsg, err) {

    }
    });
})

$(document).on('click', '.dislike', function (h) {
    h.preventDefault();
    $.ajax({
    type: 'POST',
    url: '{% url "main:dislike" %}',
    data: {
    postid: $(this).val(),
    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
    action: 'post',
    },
    success: function (json) {
    var recipedis = document.getElementById('d' + json['id']);
        if (json['result'] == 'disliked') {
        recipedis.innerHTML = '<i class="bi bi-hand-thumbs-down-fill"></i>';
        var recipeliked = document.getElementById('l' + json['id']);
        recipeliked.innerHTML = '<i class="bi bi-hand-thumbs-up"></i>'
        }
        else if (json['result'] == 'undisliked') {
        recipedis.innerHTML = '<i class="bi bi-hand-thumbs-down"></i>';
        }
    },
    error: function (xhr, errmsg, err) {

    }
    });
})

$(document).on('click', '.showmore-position-fixed', function (b) {
  b.preventDefault();
  $.ajax({
  type: 'POST',
  url: '{% url "main:showmore" %}',
  data: {
  postid: $(this).val(),
  csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
  action: 'post',
  },
  success: function (json) {
      const info = document.getElementById('showmore' + json['id']);
      if (info.style.visibility == 'visible') {
        info.style.visibility = 'hidden'
      }
      else {
        document.getElementById('time' + json['id']).textContent = json['time']
        document.getElementById('cal' + json['id']).textContent = json['calories']
        document.getElementById('genres' + json['id']).textContent = json['genres']
        info.style.visibility = 'visible'
     }

  },
  error: function (xhr, errmsg, err) {

  }
  });
}) 
</script>
{% endblock %}

django_recipe/mysite/main/templates/main/grocery_list.html
{% extends "main/base.html" %}
{% block title %}Grocery list{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'main/css/grocery.css' %}">
{% if user.is_authenticated%}
<div class="row topper" style="justify-content: space-around;">
  <h1>My Grocery List</h1>
</div>
<table>
    <tr>
      <th>Checklist</th>
      <th>Name</th>
      <th>Amount</th> 
      <th>Unit</th>
    </tr>
    <form method="post" action="#"></form>
    {% csrf_token %}
    {% for ingredient in ingredients %}
    <tr>
      {% if ingredient.checked == True %}
      <td><input class="checky" type="checkbox" value="{{ingredient.id}}" id="{{ingredient.id}}" checked></td>
      {% else %}
      <td><input class="checky" type="checkbox" value="{{ingredient.id}}" id="{{ingredient.id}}"></td>
      {% endif %}
    </form>
      <td>{{ingredient.name}}</td>
      <td>{{ingredient.amount}}</td>
      <td>{{ingredient.unit}}</td>
    </tr>

    {% endfor %}
  </table>
  <div class="row">
    <div class="col-md-12 text-center">
    <p>List of Recipes</p>
    {% for recipe in recipes%}
      <a href={{recipe.recipe.url}}>{{recipe.name}}</a>
      <br>
    {% endfor %}
    </div>
  </div>
  
{% else%}
<a href="/login">Login Here to Access Content</a>
{% endif %}
{% endblock %}
{% block javascript%}
<script>
  $(document).on('click', '.checky', function (t) {
    t.preventDefault();
    $.ajax({
    type: 'POST',
    url: '{% url "main:checky" %}',
    data: {
        postid: $(this).val(),
        csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
        action: 'post',
    },
    success: function (json) {
        var grocery = document.getElementById(json['id']);
        if (json['checked'] == 'yes') {
          grocery.checked = true;
        }
        else {
          grocery.checked = false;
        }
    },
    error: function (xhr, errmsg, err) {

    }
    });
})
</script>
{% endblock %}

django_recipe/mysite/main/templates/main/ingredient.html
{% extends "main/base.html" %}
{% block title %}Choose Ingredients {% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'main/css/ingredient.css' %}">
{% if user.is_authenticated%}
    <div class="row topper text-center">
    <h1>Choose your ingredients</h1>
    </div>
    <div class="row">
        <form method="POST" action="#">
        {% csrf_token %}
        {% if selected == 'show selected'%}
            <button type="submit" id='show' name='save' value='select'>Show Selected Ingredients Only</button>
        {% else %}
            <button type="submit" id='show' name='save' value='no select'>Show All Ingredients</button>
        {% endif %}
        </form>
    </div>

    <div class="row">
        <div class="col-md-12 col-sm-12 text-center">
            <input id="searchbar" onkeyup ="search_ingredient()" type="text" name="search" placeholder="Search ingredients..">
            <form method="POST" action="#">
                {% csrf_token %}
                {% for ingredient in non_ors%}
                    <div class="ingredient-container">
                            <div class='ingredient' id= div{{ingredient.id}}>
                                {% if user in ingredient.checked.all %}
                                <button type="submit", class = "add_or_remove", id= 'button{{ingredient.id}}', value="{{ingredient.id}}"><i class="bi bi-check-lg"></i></button>
                                {{ingredient}}
                                {% else %}
                                <button type="submit", class="add_or_remove", id= 'button{{ingredient.id}}' value="{{ingredient.id}}"><i class="bi bi-plus-lg"></i></button>
                                {{ingredient}}
                            {% endif %}
                            </div>
                    </div>
                    {% endfor %}
                </form>
            </form>
        </div>
    </div>

    {% else%}
        <a href="/login">Login Here to Access Content</a>
    {% endif %}
{% endblock %}
{% block javascript %}
<script>
    function search_ingredient(event) {
    let input = document.getElementById('searchbar').value
    input = input.toLowerCase();
    let x = document.getElementsByClassName('ingredient-container');
     
    for (i = 0; i < x.length; i++) {
        if (!x[i].innerHTML.toLowerCase().includes(input)) {
            x[i].style.display = "none";
        }
        else {
            console.log(x[i].innerHTML)
            x[i].style.display = "block";                
        }
    }
}
</script>
<script>
    $(document).on('click', '.add_or_remove', function (h) {
    h.preventDefault();
    $(this).attr('disabled', true);
    var ingredientchecked = document.getElementById('button' + $(this).val());
    if (ingredientchecked.innerHTML == '<i class="bi bi-check-lg"></i>') {
        ingredientchecked.innerHTML = '<i class="bi bi-plus-lg"></i>';
    }
    else {
        ingredientchecked.innerHTML = '<i class="bi bi-check-lg"></i>';
    }

    $.ajax({
    type: 'POST',
    url: '{% url "main:add_ingredient" %}',
    data: {
    postid: $(this).val(),
    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
    action: 'post',
    },
    success: function (json) {
        var ingredientchecked = document.getElementById('button' + json['id']);
        $(ingredientchecked).attr('disabled', false);
    },
    error: function (xhr, errmsg, err) {

    }
    });
})
</script>
{% endblock %}